name: jackblack
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.13.1+hotfix.1
  supabase_flutter: ^2.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cards/

  fonts:
    - family: Arcade
      fonts:
        - asset: fonts/ARCADECLASSIC.TTF
    - family: Minecraft
      fonts:
        - asset: fonts/Minecraftia-Regular.ttf